#!/usr/bin/env bash
# install-shortcut.command - create a macOS app icon for the DSES Spectrum
# Analyzer. Double-click in Finder, or run from a terminal. Run once per Mac;
# re-run after moving the project or refreshing the icon.
#
# It builds a "DSES Spectrum Analyzer.app" wrapper (no Terminal window) on your
# Desktop that launches launcher.sh, with the bundled pulsar icon.
#
# Optional argument: a name suffix (usually a version). With it the bundle is
# named "DSES Spectrum Analyzer <suffix>" with a distinct bundle id, so a
# second install gets its own Desktop icon instead of overwriting the first.
# Used by the in-app updater's "install a new copy" path.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SUFFIX="${1:-}"
APP_NAME="DSES Spectrum Analyzer"
BUNDLE_ID="science.dses.spectrum-analyzer"
if [ -n "$SUFFIX" ]; then
    APP_NAME="DSES Spectrum Analyzer $SUFFIX"
    # Sanitize the suffix for the reverse-DNS bundle id (alnum + dots only).
    _idsfx="$(printf '%s' "$SUFFIX" | tr -c 'A-Za-z0-9.' '-')"
    BUNDLE_ID="science.dses.spectrum-analyzer.$_idsfx"
fi
LAUNCHER="$SCRIPT_DIR/launcher.sh"
# Keep the bundle version in sync with the app (single source of truth).
APP_VERSION="$(grep -oE '^APP_VERSION[[:space:]]*=[[:space:]]*"[^"]+"' \
    "$SCRIPT_DIR/dses_spectrum_analyzer.py" 2>/dev/null \
    | head -n1 | sed -E 's/.*"([^"]+)".*/\1/')"
[ -z "$APP_VERSION" ] && APP_VERSION="1.0.0"
PNG="$SCRIPT_DIR/icons/dses_sa.png"
ICNS="$SCRIPT_DIR/icons/dses_sa.icns"
DEST_DIR="$HOME/Desktop"
APP="$DEST_DIR/$APP_NAME.app"

if [ ! -f "$LAUNCHER" ]; then
    echo "launcher.sh not found next to this script ($LAUNCHER). Aborting." >&2
    exit 1
fi

# A release zip built on Windows (or unzipped by a tool that drops Unix mode
# bits) can leave launcher.sh non-executable, which makes the .app's
# `exec launcher.sh` fail with "Permission denied". Restore +x now so both this
# .app and a direct ./launcher.sh work. chmod is idempotent.
chmod +x "$LAUNCHER" 2>/dev/null || true

# Build the .icns from the PNG if it isn't committed/present (needs macOS tools).
if [ ! -f "$ICNS" ]; then
    if [ -f "$PNG" ] && command -v sips >/dev/null && command -v iconutil >/dev/null; then
        echo "Building icons/dses_sa.icns from dses_sa.png ..."
        set="$(mktemp -d)/dses_sa.iconset"; mkdir -p "$set"
        sips -z 16  16  "$PNG" --out "$set/icon_16x16.png"      >/dev/null
        sips -z 32  32  "$PNG" --out "$set/icon_16x16@2x.png"   >/dev/null
        sips -z 32  32  "$PNG" --out "$set/icon_32x32.png"      >/dev/null
        sips -z 64  64  "$PNG" --out "$set/icon_32x32@2x.png"   >/dev/null
        sips -z 128 128 "$PNG" --out "$set/icon_128x128.png"    >/dev/null
        sips -z 256 256 "$PNG" --out "$set/icon_128x128@2x.png" >/dev/null
        sips -z 256 256 "$PNG" --out "$set/icon_256x256.png"    >/dev/null
        iconutil -c icns "$set" -o "$ICNS"
        rm -rf "$(dirname "$set")"
    else
        echo "Note: no icons/dses_sa.icns and can't build one; the app will use"
        echo "      the generic icon. Generate icons/dses_sa.png first." >&2
    fi
fi

# (Re)create the bundle from scratch so re-running always refreshes it.
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# Wrapper executable: launch the analyzer (no Terminal), logging for debug.
cat > "$APP/Contents/MacOS/launch" <<EOF
#!/bin/bash
# Auto-generated by install-shortcut.command. Points at the project that
# created it; re-run install-shortcut.command if you move the project.
LOG="\$HOME/Library/Logs/DSES_Spectrum_Analyzer.log"
# Self-heal: an in-place update from a zip without Unix mode bits (e.g. a
# Windows-built release, or an updater that extracts with zipfile.extractall)
# can leave launcher.sh non-executable, which would make the exec below fail
# with "Permission denied". Restoring +x on every launch makes the icon robust
# against that regardless of how the install got there. chmod is idempotent.
chmod +x "$LAUNCHER" 2>/dev/null || true
exec "$LAUNCHER" >>"\$LOG" 2>&1
EOF
chmod +x "$APP/Contents/MacOS/launch"

if [ -f "$ICNS" ]; then
    cp "$ICNS" "$APP/Contents/Resources/dses_sa.icns"
    ICON_KEY='    <key>CFBundleIconFile</key>
    <string>dses_sa</string>'
else
    ICON_KEY=''
fi

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>$APP_NAME</string>
    <key>CFBundleDisplayName</key>
    <string>$APP_NAME</string>
    <key>CFBundleIdentifier</key>
    <string>$BUNDLE_ID</string>
    <key>CFBundleExecutable</key>
    <string>launch</string>
$ICON_KEY
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>$APP_VERSION</string>
    <key>CFBundleVersion</key>
    <string>$APP_VERSION</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSBackgroundOnly</key>
    <false/>
</dict>
</plist>
EOF

# Nudge Finder/LaunchServices to pick up the new bundle + icon.
touch "$APP"
/usr/bin/touch "$APP/Contents/Info.plist"
if command -v /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister >/dev/null 2>&1; then
    /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f "$APP" || true
fi

echo "Created: $APP"
echo "Double-click it on your Desktop to launch the analyzer."
echo "(Logs: ~/Library/Logs/DSES_Spectrum_Analyzer.log)"
